# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ehossain <ehossain@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/22 12:50:50 by ehossain          #+#    #+#              #
#    Updated: 2026/04/22 12:54:28 by ehossain         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= phonebook
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
SRC = main.cpp \
      Contact.class.cpp \
      PhoneBook.class.cpp \
OBJ = 

NAME: $(SRC)

OBJ:

